### ISSUE TITLE
Ensure file integrity

### ISSUE THREAD

**Issue by schneijan** [IPVS-AS/MBP#12]
In order to make the application more resilient, an approach is needed to ensure the integrity of the files (scripts) that were transferred to the dedicated network device while deployment.

**Comment by hirmerpl** [comment]
- [ ] Limit upload file size
- [ ] Add a list of unallowed file types.

**Comment by schneijan** [comment]
Integrated a hash-based integrity check. File size is currently limited to 10 MB, I think this should be sufficient. At the moment I do not see why we should forbid certain file types, security-wise this does not make any difference.
