### ISSUE TITLE
Create operator documentation

### ISSUE THREAD

**Issue by schneijan** [IPVS-AS/MBP#144]
We need an operator documentation and guidelines which describe how to create operator scripts and which command line parameters are provided to them by the MBP. In addition, there should be a warning about possible side-effects as described in #135.

**Comment by tatianegava** [comment]
@schneijan hey Jan, can we talk about this topic then you can provide to me more details and I can write it down?

**Comment by ana-silva** [comment]
- A wiki page was created for this: https://github.com/IPVS-AS/MBP/wiki/How-to-register-an-Operator
- each operator provided in the [MBP Operators repository](https://github.com/IPVS-AS/MBP/tree/master/resources/operators) indicates in its [README.md](https://github.com/IPVS-AS/MBP/blob/master/resources/operators/extraction/temperature_stub_param/README.md) which parameters are expected
