### ISSUE TITLE
CEP: Delete rules on deletion of actions and conditions gracefully

### ISSUE THREAD

**Issue by schneijan** [IPVS-AS/MBP#180]
Rules should be deleted in a graceful way (similar to actuators/sensors) in case its actions/conditions are deleted.

**Comment by lauracorssac** [comment]
Just to check if I understood. The solution for that issue would be an improvement of the message shown in the confirmation of deletion of an an action or condition? The confirmation should show the rule definitions that will be deleted when the user procedes, like this one: 

The following components are currently using this action and will be deleted as well:
- rule definition 

Did I understand right? :)

**Comment by lauracorssac** [comment]
And, in case I understood it right, do we have an endpoint, such as the one called by `DeviceService.getUsingComponents` , that retrieves the rules that depend on a particular action/condition?

**Comment by schneijan** [comment]
Yes, you are completly right :-) It's almost the same as for the actuators/sensors, in case the user wants to delete an operator or a device.

> And, in case I understood it right, do we have an endpoint, such as the one called by `DeviceService.getUsingComponents` , that retrieves the rules that depend on a particular action/condition?
Unfortunately not. We even do not have a REST interface/controller for this yet. I guess we need one similar to [RestComponentFilterController.java](https://github.com/IPVS-AS/MBP/blob/master/src/main/java/org/citopt/connde/web/rest/RestComponentFilterController.java). The implementation should be quite similar, but we probably do not need to convert actions/trigger to excerpts, as these domain objects do not carry sensitive information (like passwords or RSA keys), if I recall correctly.
