### ISSUE TITLE
Problems after VM restart

### ISSUE THREAD

**Issue by hirmerpl** [IPVS-AS/MBP#23]
After restart of a VM, it takes a long time (~30 minutes) until the MBP is available again. Restarting Tomcat Server etc. does not help with this problem.

**Comment by hirmerpl** [comment]
How to reproduce:

1. Install MBP on VM
2. Select  "soft restart VM" in Openstack UI
3. Try to access MBP

**Comment by ana-silva** [comment]
solution is to change java configuration as below:
https://stackoverflow.com/questions/26431922/tomcat7-starts-too-late-on-ubuntu-14-04-x64-digitalocean/26432537#26432537

TODOs:
[] install script should do this
[] update documentation
