### ISSUE TITLE
SSH connection to local virtual machines (e.g., VirtualBox) does not work

### ISSUE THREAD

**Issue by hirmerpl** [IPVS-AS/MBP#232]

**Comment by ana-silva** [comment]
For a MBP running on Windows OS:
- A guide for configuring a local virtual machine in Hyper-V to be able to communicate with  the MBP running in the machine hosting Hyper-V is provided in the [MBP Wiki](https://github.com/IPVS-AS/MBP/wiki/Hyper-V-Device).
