### ISSUE TITLE
Allow user/password login instead of RSA

### ISSUE THREAD

**Issue by hirmerpl** [IPVS-AS/MBP#236]
From Percom review: "while security is important, in some use cases RSA key seems to be excessive, but MBP does not allow to register a device without it"

**Comment by lucio-lpf** [comment]
I have a doubt: The task consists only in "let users create devices without an RSA" (just change the RSA field to not-mandatory) or I must implement de connection without an RSA key.

**Comment by hirmerpl** [comment]
changing the RSA field to not-mandotary is not enough because we have to make sure that either the user name and RSA key are provided or user name and password. So we have to check whether a password was given if the RSA key field is empty.

**Comment by lucio-lpf** [comment]
Understood! Thank you

**Comment by schneijan** [comment]
This will probably need some rework of [SSHSession.java](https://github.com/IPVS-AS/MBP/blob/master/src/main/java/org/citopt/connde/service/ssh/SSHSession.java) which unfortunately tends to be quite brittle. At the moment, it always uses the SSH key to connect and then (if necessary) transmits the given password for every command that is supposed to be executed.

I personally don't like the SSH library (JSCH) we are using at the moment. If you know a better/more robust one, feel free to replace it. :-) [SSHJ](https://github.com/hierynomus/sshj) looks promising, but I haven't tried it yet.

**Comment by lucio-lpf** [comment]
<img width="1610" alt="Captura de Tela 2020-04-02 às 09 02 25" src="https://user-images.githubusercontent.com/8583169/78220549-0e437200-74c2-11ea-90e0-31ac213eab91.png">
<img width="1360" alt="Captura de Tela 2020-04-02 às 09 01 43" src="https://user-images.githubusercontent.com/8583169/78220558-11d6f900-74c2-11ea-8b73-1c369d8cf621.png">
