### ISSUE TITLE
Add icons for deletion/edit instead of Text

### ISSUE THREAD

**Issue by hirmerpl** [IPVS-AS/MBP#269]
Should look like in the user view:

![grafik](https://user-images.githubusercontent.com/7569371/78123889-27d7b180-740f-11ea-8427-42b45fa4dc44.png)

Furthermore, find an icon for manage user.

**Comment by lucio-lpf** [comment]
@hirmerpl I am a little confused. The version on master already looks like your print: 
![Screenshot from 2020-04-06 14-21-42](https://user-images.githubusercontent.com/8583169/78559545-d49d9e80-7814-11ea-8b01-b23d4aa095e0.png)

**Comment by schneijan** [comment]
I guess this issue is about applying this look and feel to the pages of the other entities as well, e.g. to the device list, the operator list, the sensor list etc.
