### ISSUE TITLE
Implement python library to ease operator scripts creation

### ISSUE THREAD

**Issue by ana-silva** [IPVS-AS/MBP#274]
Currently all logic to send data to the MBP is included in the operator scripts. Since this is required for all scripts, this code should be outsorced to a library `MBPclient.py` that should be imported in the operator scripts. 
The `MBPclient.py` should include for example the MQTT client communicating publishing data to the MBP MQTT Broker.

**Comment by schneijan** [comment]
This includes just the logic for running an operator, right? The logic for starting/stopping of the operator will still need to be implemented in separate scripts, won't it? 

A more sophisticated approach could be to completly move away from operator scripts and use messaging instead which is of course more reliable and configurable (in terms of QoS) than executing bash files over SSH. With MQTT we are already using a messaging system, why not use it for starting and stopping of operators as well. But of course this would cause some effort.
