### ISSUE TITLE
Make creation of properties file on devices more robust

### ISSUE THREAD

**Issue by schneijan** [IPVS-AS/MBP#317]
If the MBP is unable to determine the broker's IP address, the MBP fails to create the properties file on deployment

**Comment by ana-silva** [comment]
Location where the properties file is created on devices: [code](https://github.com/IPVS-AS/MBP/blob/c492a22861b12ab179871feb097b64721ac09520/src/main/java/org/citopt/connde/service/deploy/SSHDeployer.java#L314)

**Comment by schneijan** [comment]
Cannot reproduce anymore
