### ISSUE TITLE
Moving the cursor around with the arrow keys - MacBook Google Chrome

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#321]
It is not possible move the cursor left/right with the arrow keys when creating new actuators, operators and sensors:

<img width="800" alt="Screenshot 2020-07-14 at 12 57 23" src="https://user-images.githubusercontent.com/44437898/87418230-a11b9e80-c5d1-11ea-8aa3-4907c2e410d2.png">

**Comment by tatianegava** [comment]
MacBook
GoogleChrome

**Comment by schneijan** [comment]
Hi,

do you refer to the input field (e.g. the field in which on the sreenshot "Test arrow" is written)?

**Comment by tatianegava** [comment]
Hi :) 
Actually in all fields which I can type text (not the drop box) in my computer the arrow left/right does nor work.

**Comment by tatianegava** [comment]
Pascal tested in his windows and it worked, however in my MAC no :(

**Comment by schneijan** [comment]
@ulusal Would it be possible for you to check this as well? 
I have no issues with it on my Chromium-based browser.

**Comment by ana-silva** [comment]
@lauracorssac can you check this as well, in case you still have the MBP installed on your MAC? thanks :)

**Comment by lauracorssac** [comment]
@ana-silva For me, for me it is working like that: I need to press TAB to change between the input types (name, act type, control operators, device) and I use the arrows to choose between the options when it is the case. For example, for switching between the devices available I can use the arrow to navigate the list.

**Comment by tatianegava** [comment]
@lauracorssac Hey Laura. :) Can you also use the arrows to walk between the letters in your inputs?

**Comment by lauracorssac** [comment]
@tatianegava Hey, Tatiane! Yes, for me, this is working as well. :)

**Comment by tatianegava** [comment]
Then it is my computer. I will close the issue.
