### ISSUE TITLE
Include a edit Button in Devices, Actuators, Sensors and Operator

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#324]
Include an edit Button in Devices, Actuators, Sensors and Operator.

<img width="940" alt="Screenshot 2020-07-14 at 13 18 56" src="https://user-images.githubusercontent.com/44437898/87420013-c958cc80-c5d4-11ea-822c-a3d77d42f680.png">

**Comment by schneijan** [comment]
Duplicates #68

**Comment by tatianegava** [comment]
Hi, 
Thanks Jan! Should I delete it? :)

**Comment by schneijan** [comment]
We could just close it :-)
