### ISSUE TITLE
Include User Overview Rule Condition

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#325]
Include User Overview Rule Condition more like the condition & aggregation view.

<img width="919" alt="Screenshot 2020-07-14 at 13 22 15" src="https://user-images.githubusercontent.com/44437898/87420155-0ae97780-c5d5-11ea-8a75-4b7ed424930b.png">

<img width="594" alt="Screenshot 2020-07-14 at 13 23 13" src="https://user-images.githubusercontent.com/44437898/87420211-2ce2fa00-c5d5-11ea-8856-133e90baf00e.png">

**Comment by schneijan** [comment]
That's not possible at the moment, because the query might be user-defined (last step of the condition wizard).
