### ISSUE TITLE
Display 'device_code' parameter in New Operator only if OAuth2 is used

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#329]
1. The Parameters should be showed empty?
2. If I leave the device_code parameter, which is showed as standard, this parameter is not requested in the deployment. However, if I only change device_code Name to device_code2 Name, this field is required in the deployment.
3. If I delete the parameter clicking in Mull, close the pop-up window and click in the "+", the device_code Name comes empty. But If i click on Devices, then again in operator, the device_code Name comes not empty. Can be cache? 

<img width="1267" alt="Screenshot 2020-07-14 at 14 08 24" src="https://user-images.githubusercontent.com/44437898/87424459-45a2de00-c5dc-11ea-91ee-941cab43435f.png">

**Comment by schneijan** [comment]
I have no clue what this device_code parameter is, but it seems to be related to OAuth.
@marvin21 Can you help here?

**Comment by marvin21** [comment]
Hi everyone, 

the device_code parameter is used during the OAuth authorization process. 

If you are using a secured broker with OAuth2, then the device_code is necessary for the device. During the deployment, the device will request a token with this code. The parameter is filled in automatically, if you create a new sensor and open this sensor for the deployment.

If you are not using a secured broker, you can just ignore this parameter (remove it), and add you operator. Then this parameter should not appear in the sensor view.

@tatianegava : Can you create your operator and add it to a device? Or are there any issues, if you remove the device_code parameter?

For more information, have a look at the wiki:
https://github.com/IPVS-AS/MBP/wiki/OAuth2-Authentication#extraction-control-operators-view

To determine, if you are using a secured broker, have a look in your settings at the MBP:
![grafik](https://user-images.githubusercontent.com/9257620/87458475-58cca280-c60a-11ea-8191-ca71d14eb39d.png)

To avoid confusion in the future, I can create an issue to remove this parameter completely from the user interface, if no OAuth is used.

**Comment by tatianegava** [comment]
Hi @marvin21 :)
I am using local broker without OAth2. I can create an Operator with or without the device_code parameter, and never this parameter is requested to me, even if I created my operator with it. Furthermore I can add it to a device and works. 
My question is more about if makes sense only appear this device_code when it is mandatory and not all the time. :)
Tati

**Comment by marvin21** [comment]
Hi @tatianegava 
I get your point. 
I will optimize the device_code parameter to only be displayed if OAuth2 is used.

**Comment by hirmerpl** [comment]
how is the progress here?

**Comment by marvin21** [comment]
Work in progress, should be finished by the end of this month.

**Comment by schneijan** [comment]
Fixed in branch `first_release_fixes`
