### ISSUE TITLE
Create a search in Operator

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#330]
Create a search in Operators. If the list is too big, it would help to find the operator.

<img width="1278" alt="Screenshot 2020-07-14 at 14 25 17" src="https://user-images.githubusercontent.com/44437898/87425423-e645cd80-c5dd-11ea-8593-f0f0fd319352.png">

**Comment by schneijan** [comment]
Imo this is something we should implement for all entities by adjusting the generic ListItemController.
