### ISSUE TITLE
Standardize all icons and color palette

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#332]
standardize all icons and color palette

**Comment by tatianegava** [comment]
@schneijan Hi Jan, do you know where is saved our icons which we use in MBP?

**Comment by schneijan** [comment]
Hi,
images and resources are stored in [src/main/resources/static/images](https://github.com/IPVS-AS/MBP/tree/master/src/main/resources/static/images). The remaining icons (menu bar, ...) are part of a [Google font](https://github.com/IPVS-AS/MBP/blob/master/src/main/resources/static/plugins/google-fonts/material-icons.css)

**Comment by tatianegava** [comment]
Thanks a lot!! :)

**Comment by ana-silva** [comment]
Developer documentation with guidelines was added in the MBP Wiki:
* https://github.com/IPVS-AS/MBP/wiki/For-developers 
* https://github.com/IPVS-AS/MBP/wiki/Design-Manual
