### ISSUE TITLE
Share Sensor and Operator

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#333]
When a Sensor is shared, the operator linked to the sensor should be also shared, however it is only shared the sensor without creating an operator.

**Comment by schneijan** [comment]
Imo this is by purpose. The user with which a sensor is shared should only be able to use exactly this sensor and he should not be able to create further sensors with the same operator, as long as the operator is not shared as well.

**Comment by tatianegava** [comment]
But the sensor is nothing without the operator. Is only a name.

**Comment by schneijan** [comment]
The sensor can still be deployed and used within rules. The operator is there, it's only hidden for the user (when not shared).

**Comment by tatianegava** [comment]
Hi Jan, thanks a lot for your explanation. I have one more question...
If someone shared with me a sensor, but I already have plenty of them and one day I want to understand the operator from this sensor which was shared with me. But I do not remember someone shared it with me, it would not be good have the operator also? It is only a usability question.

**Comment by schneijan** [comment]
I think there are valid arguments for both possibilities :-)
@hirmerpl Could you please decide which way to go?

**Comment by hirmerpl** [comment]
I would share sensors and operators seperately. Usually, people are interested in sharing their data. If I also share my operator with my data, people tend to get access to a lot of operators, the list gets longer and longer and they easily get overwhelmed.

**Comment by schneijan** [comment]
Since the sharing functionality is now implemented in a very different way, this issue is no longer an issue.
