### ISSUE TITLE
Bug with register user

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#334]
In a normal user, which is not an Admin, you can create a new user, however when it is created a new user TestTati, the first message is that the user can not be created: 

<img width="1240" alt="Screenshot 2020-07-14 at 15 17 07" src="https://user-images.githubusercontent.com/44437898/87430435-82bf9e00-c5e5-11ea-96a0-c5951b717910.png">

Then I tried to create again the same user, the message says the user was already in use:

<img width="1266" alt="Screenshot 2020-07-14 at 15 16 06" src="https://user-images.githubusercontent.com/44437898/87430513-9834c800-c5e5-11ea-8db5-b2580d465b7a.png">

Finally I access the admin user, and the user is there, however I can not see it in the normal user and there was only error messages.

<img width="1055" alt="Screenshot 2020-07-14 at 15 23 17" src="https://user-images.githubusercontent.com/44437898/87430763-f792d800-c5e5-11ea-8947-a0602bcdb13f.png">

**Comment by schneijan** [comment]
Registration of new users should only be possible for admin users, probably.

**Comment by tatianegava** [comment]
I totally agree with you. Then we should take the feature out from a normal user.
