### ISSUE TITLE
How to start  (first page on MBP) excludable 

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#341]
The first page should have the option to exclude/hide the How to start.
If the user is already comfortable with the tool, the how to start could be hidden and in this way, the user would have in home the dashboard only. 

Then we will have more space to probably have more  information in the dashboard in future :) 

![image](https://user-images.githubusercontent.com/44437898/87761236-69029e80-c811-11ea-9ecd-99cdb909c4c2.png)

**Comment by tatianegava** [comment]
Hi @schneijan :)
I have reviewed your change, however what I meant here it is like when we use a new software, it is provided a tutorial for beginners and later it disappears or you can choose to close it forever.  
Your solution hides only when I am at the page, if I change and I go back to home, it is opened again.

**Comment by hirmerpl** [comment]
It is ok that it does not disappear forever, it could happen that people need the tutorial again after some time.
However, when I hide the tutorial and come back, it should stay hidden until I decide to show it again. This requires setting a cookie.
