### ISSUE TITLE
Use the 'Delete Icon' (trash can) instead of the text 'Delete' for buttons 

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#344]
we need to standardize our Delete button, for this reason we are going  to use from now on only the trash can

![image](https://user-images.githubusercontent.com/44437898/87923384-b125f900-ca7d-11ea-812d-508fc068ff55.png)

Places we need to update:

![image](https://user-images.githubusercontent.com/44437898/87923407-bb47f780-ca7d-11ea-8037-d8f86e8c6b61.png)

**Comment by tatianegava** [comment]
Also in Rules

![image](https://user-images.githubusercontent.com/44437898/87923495-e2062e00-ca7d-11ea-8ace-7929559ea762.png)

![image](https://user-images.githubusercontent.com/44437898/87923503-e599b500-ca7d-11ea-8cf2-6abcd5ad6a04.png)

**Comment by ana-silva** [comment]
duplicate: https://github.com/IPVS-AS/MBP/issues/269

**Comment by tatianegava** [comment]
#356
