### ISSUE TITLE
Use MBP standard colours in the Rule modeling tool

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#346]
![image](https://user-images.githubusercontent.com/44437898/87924486-44136300-ca7f-11ea-97b4-5631d02d917a.png)

![image](https://user-images.githubusercontent.com/44437898/87924962-e6cbe180-ca7f-11ea-8689-1af626fd580d.png)

Standardize both:
![image](https://user-images.githubusercontent.com/44437898/87924943-e03d6a00-ca7f-11ea-821b-676d47bcec8f.png)

**Comment by schneijan** [comment]
Hi,

I changed the colors of the steps and the next/previous buttons, see branch rule_conds_colors. However, for the other points you mentioned I am unsure what should be changed and to what color. Could you please describe which element in detail should be changed to the grey of the drop events area and how the and/or buttons should look like? This would be helpful.

For the and/or/before connectors I am unsure if they really need to be changed. From my point of view they do not belong to the overall design but are components that represent some logic that the user wants to define, so for me it would be fine if their colors do not match the standardized ones. How do you see it?

**Comment by ana-silva** [comment]
Hi @schneijan, here some thoughts:

- "colors of the steps and the next/previous buttons, see branch rule_conds_colors" --> great :)
- I think AND/OR should stay like they are right now --> 
![image](https://user-images.githubusercontent.com/17008080/106627111-be698780-6578-11eb-80ae-98c4a9bb00cd.png)
- to the and/or/before connectors: i also think is fine if they stay in the current colors
- if is not much trouble, i would change the add buttons to the MBP blue, i think we use overall blue for 'Add' -->
![image](https://user-images.githubusercontent.com/17008080/106627991-9fb7c080-6579-11eb-813c-e7cf28c66685.png)

**Comment by ana-silva** [comment]
Hi @schneijan, is the branch `rule_conds_colors` ready for a PR? I undestood the color change was already done...

**Comment by schneijan** [comment]
I updated this branch and adjusted the buttons. If this is fine for you, you can merge it. :-)
![image](https://user-images.githubusercontent.com/44969037/109237864-bd6ff280-77d2-11eb-8ebf-587d56ba5ca9.png)
