### ISSUE TITLE
"How to start/ Welcome" update text 

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#348]
The current steps are for our Modeling Tool, however the feature is not stable , for this reason we need to change the text in this welcome to be the similar to our [Quick Start](https://github.com/IPVS-AS/MBP/wiki/Quick-Start). 

Bold -> Link for the register page

Welcome to MBP your IoT Platform!
We are happy that you have chosen MBP to help you to manage and control your IoT devices!
Lets start to set up your IoT environment in 6 steps:
Step 1 - Register your **devices** of your environment.
Step 2 – Create extraction/control **operators** for your sensor and actuators. Control operator is an optional step, it is needed only if you have actuators in your environment.
Step 3 – Register a new **sensor** which is connected to the device.
Step 4 – Install the Sensor Operator in the Device. (Deploy)
Step 5 – Start operators
Step 6 – **Rule** creation
Steps 3-5 is the same to create a new **actuator**.

Another alternative way to build your IoT network is through the Modeling Tool. In this view, you build your network in a more visual way. Click **here** to go to this view or click the Modeling Tool on the right menu.

**Comment by schneijan** [comment]
Why is the modelling tool not 100% implemented, i.e. which features are missing?

**Comment by tatianegava** [comment]
Hi @schneijan :) I do not know all details, I will test and see it this week. It was only what I heard. 
I can share with you my doubts and we discuss in this next weeks :)

**Comment by hirmerpl** [comment]
It is not about feature completeness, I would say that all features of the modeling tool are implemented. However, using the environment modeling tool is not as stable and easy to understand as registering the devices etc. manually. That is why we should describe the manual way on the home page and add a link to the modeling tool as an alternative approach. What do you think?

**Comment by schneijan** [comment]
Sounds reasonable 👍

**Comment by tatianegava** [comment]
Bold -> Link for the register page

Welcome to MBP your IoT Platform!
We are happy that you have chosen MBP to help you to manage and control your IoT devices!
Lets start to set up your IoT environment in 6 steps:
  Step 1 -  Register your devices of your environment.
  Step 2 – Create extraction/control operators for your sensor and actuators. Control operator is an optional step,   it is needed only if you have actuators in your environment.
  Step 3 – Register a new sensor which is connected to the device. 
  Step 4 – Install the Sensor Operator in the Device. (Deploy)
  Step 5 – Start operators
  Step 6 –  Rule creation 
Steps 3-5 is the same to create a new actuator. 

Another alternative way to build your IoT network is through the Modeling Tool. In this view you build your network in a more visual way. Click here to go to this view or click the Modeling Tool on the right menu.

**Comment by tatianegava** [comment]
@schneijan Hi :)
I saw you have changed the steps, for this reason I have some questions:

1. Register a RSA. Do I need to perform this step? I have created my connection without it. Is it optional or not?
2.  Could you please include: Step 1...2...?
3. In step 2, could you please include like it: Step 2 – Create **extraction/control** operators for your sensor and actuators. **Control operator is an optional step, it is needed only if you have actuators in your environment.**
4. Change the word Deploy to Install.
5. "and put them into operation." to "and put them into operation (start)".
