### ISSUE TITLE
Extra infos in Sensor and Actuator

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#350]
Sensor/Actuator State. I need to go back one page to see the state, in the details  I can only see the Device State

There is a value statistic, it would be good show here also dates/hour. For example: Last value. When was it? Average. From when to when?

**Comment by schneijan** [comment]
The sensor/actuator state is already displayed on top of the details page.

**Comment by tatianegava** [comment]
@schneijan it is true what you mentioned, I was trying to find this standard box which we use for the states. 
Maybe it would be better follow a standard, what do you think?

**Comment by schneijan** [comment]
I personally like the current solution.
