### ISSUE TITLE
The system should not allow the registration of new users by a NON-Administrator user - Fail

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#362]
When a user is logged as a NON-Administrator User the following page should appear EMPTY or should NOT be able to access it: [http://localhost:8080/MBP/view/users](<http://localhost:8080/MBP/view/users>)

<br>

![null](<blob:https://mbp.testquality.com/72bd3df4-2adc-4858-bbe6-197a9d2cb27e>)

This page should be showed only for Admin Users and not for NON-Admin users.

<br>

**Comment by tatianegava** [comment]
https://mbp.testquality.com defect [D1](https://mbp.testquality.com/project/11022/result/2096151/defect/7176). Do not remove or edit.

**Comment by schneijan** [comment]
>The system should not allow the registration of new users by a NON-Administrator user
Well, this must be allowed, otherwise users cannot register themselves.

**Comment by tatianegava** [comment]
https://mbp.testquality.com requirement [R6](https://mbp.testquality.com/project/11022/testcase/253522/requirement/10711). Do not remove or edit.
