### ISSUE TITLE
Actuator & Adapter Validator error: invalid property "type"

### ISSUE THREAD

**Issue by amil-i** [IPVS-AS/MBP#37]
"Type" not changed to "Adapter" in ActuatorValidator & AdapterValidator, unable to create a new Actuator.

**Comment by schneijan** [comment]
Hi Amil,
you are right, I stumbled across this myself while working on #4. The issue will be fixed as soon as #36 is merged into master (https://github.com/IPVS-AS/MBP/pull/36/files#diff-e1e13536eeff328d01f7c6004564c0c7). Probably it would have been better if I tracked this issue. Sorry for the confusion!
