### ISSUE TITLE
Flag default operators

### ISSUE THREAD

**Issue by schneijan** [IPVS-AS/MBP#467]
Default operators should be flagged, so that they can be distinguished from user-created operators. This even allows duplicate detection on default operators, avoiding that the same default operator is added more than one time.

**Comment by ana-silva** [comment]
I've noticed the following behaviour related to default operators: 
After creating a default operator as admin, I created a new user and switched to it. Then by loading the list of operators as this non-admin user, the error message 'Could not load approved users' pop up (see screenshot). 
I think by using flags for default operators, this can be solved as well.

![grafik](https://user-images.githubusercontent.com/17008080/93474085-30597100-f8f7-11ea-9be0-a45df188ffe9.png)
