### ISSUE TITLE
Available monitoring operators STATE ISSUE

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#474]
My Monitoring CPU Operator is working, MBP is receiving data from Raspberry, however the monitoring operator STATUS is unknown. Is it right?
Another question, after the monitoring operator is enabled, the button stops to work. I can not turn off or on.

Issue was found in Opera Browser in Windows.

![image](https://user-images.githubusercontent.com/44437898/94848828-d7c0c280-0424-11eb-9a8e-5ed1dbb46137.png)

![image](https://user-images.githubusercontent.com/44437898/94848902-f3c46400-0424-11eb-9166-09cbbd0b6b76.png)

**Comment by tatianegava** [comment]
An extra information. I have created a new device, the same I have tested above.  The Monitoring Operator does not work at all:

![image](https://user-images.githubusercontent.com/44437898/94852960-ee6a1800-042a-11eb-9e2e-0d3c61246a7c.png)

**Comment by schneijan** [comment]
Do you know if this is still a problem?

**Comment by tatianegava** [comment]
Tested again, and there is no problem.
