### ISSUE TITLE
Repository contains unnecessary files / dependencies

### ISSUE THREAD

**Issue by ana-silva** [IPVS-AS/MBP#512]
Unnecessary files and dependencies should be deleted.

- [x] remove unnecessary files from root folder
- [x] remove unused dependencies from `pom.xml`
- [x] check if `install-advertise.sh` and corresponding code should be in the `first-release`  
- [ ] check [adapter-scripts folder](https://github.com/IPVS-AS/MBP/tree/master/resources/adapter-scripts) and delete content or merge into [operators folder](https://github.com/IPVS-AS/MBP/tree/master/resources/operators)

![image](https://user-images.githubusercontent.com/17008080/105478479-85d9cc00-5ca3-11eb-90b8-97638c55843d.png)

**Comment by schneijan** [comment]
I worked on the first three bullet points and created a corresponding PR. In terms of the last bullet point I am not sure whether we still need the data in this folder.
