### ISSUE TITLE
LF vs. CRLF

### ISSUE THREAD

**Issue by schneijan** [IPVS-AS/MBP#513]
The MBP is currently unable to work with operator scripts that use Windows line endings (CRLF) instead of Unix line endings (LF). We need either to find a fix for this issue or to document this problem.

**Comment by ana-silva** [comment]
I added warning messages in the wiki, but we still shoud fix this at some point.
https://github.com/IPVS-AS/MBP/wiki/How-to-register-operators
https://github.com/IPVS-AS/MBP/wiki/Quick-Start#2-registration-of-the-extraction-operator
