### ISSUE TITLE
Problems in the user view

### ISSUE THREAD

**Issue by ana-silva** [IPVS-AS/MBP#516]
Problems:
* As an Admin, the button to access users view is missing. 
![image](https://user-images.githubusercontent.com/17008080/106479423-9ca1cf00-64aa-11eb-92ab-fba3c8a0d1d7.png)
* As an Admin, accessing the users view through the known URL (http://localhost:8080/MBP/view/users), the view seems to be broken. As a normal user, the same is shown as bellow.
![image](https://user-images.githubusercontent.com/17008080/106479609-ce1a9a80-64aa-11eb-9747-69f5378543a7.png)

**Comment by schneijan** [comment]
If you agree with me, I would move the menu item to the main menu and make it visible only for admin users there. Then we can get rid of the small context menu with only one entry.

**Comment by ana-silva** [comment]
Hi @schneijan, the user management view is working again, changing passwords worked as well. 
However, i was able to delete the standard users and also the Admin. I think it should not be possible to delete the admin and the standard users.
