### ISSUE TITLE
Inconsistent UI elements

### ISSUE THREAD

**Issue by ana-silva** [IPVS-AS/MBP#517]
UI elements should be consistent, same elements should look alike. 

* **register new device modal dialog**: in the following Figure, the drop-down menu for policies does not look like the other two drop-downs in the same dialog.

<p align="center">
<img src="https://user-images.githubusercontent.com/17008080/106520978-d7712a80-64dd-11eb-86c9-765a0ff049cf.png" width="500">
</p>

**Comment by johnmhayde** [comment]
Hi @ana-silva, I have a project for a software methodology class to contribute to an open source repo and I am very interested in this project. Could I be assigned to this issue?

**Comment by ana-silva** [comment]
Hi @johnmhayde we have planned already this issue for @schneijan, since it involves further more components than I originally thought. Anyway, great that you want to contribute, feel free to have a look on the other issues.

**Comment by schneijan** [comment]
Done within #585
