### ISSUE TITLE
Policy Condition window cannot be closed

### ISSUE THREAD

**Issue by schneijan** [IPVS-AS/MBP#520]
At the moment it's not possible to close the modal for policy condition creation.

**Comment by ana-silva** [comment]
This can be reproduced after trying to register a policy condition without filling all mandatory parameters, what also throws a null point exception :(

![image](https://user-images.githubusercontent.com/17008080/106915599-7e380f80-6706-11eb-8d4f-c37db96b42b6.png)

```
SEVERE: Servlet.service() for servlet [dispatcher] in context with path [/MBP] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "de.ipvs.as.mbp.domain.access_control.jquerybuilder.JQBOutput.getRules()" because "jqbOutput" is null] with root cause
java.lang.NullPointerException: Cannot invoke "de.ipvs.as.mbp.domain.access_control.jquerybuilder.JQBOutput.getRules()" because "jqbOutput" is null
```
