### ISSUE TITLE
No values are displayed in charts

### ISSUE THREAD

**Issue by hirmerpl** [IPVS-AS/MBP#522]
I tested on our master Jenkins build and there are no values visible in the charts, even though the sensor is successfully deployed and started and data arrives in the MQTT broker.

**Comment by schneijan** [comment]
Which broker did you use?

**Comment by hirmerpl** [comment]
I used the workaround to put the IP of the machine as remote broker since the lokal broker did not work. Do you see values on the Jenkins master?

**Comment by ana-silva** [comment]
Running the MBP locally and deploying the operator on another PC in my local network works fine. I guess this is a Jenkins/openstack issue?

**Comment by schneijan** [comment]
On Jenkins an old version is running, unfortunately. The whole pipeline is somehow broken, at least tomcat does not accept builds anymore. Maybe it's the easiest way to re-install the whole VM.

**Comment by ana-silva** [comment]
@hirmerpl is this still an issue?
