### ISSUE TITLE
[Rules / Actions Test] The system should allow sharing rule actions - Block

### ISSUE THREAD

**Issue by katja-seb** [IPVS-AS/MBP#532]
#### Precondition
<p>MPB installed</p><p>User is logged in</p><p>User is not joanna_soares and not Administrator</p><p>There is action created (TS12 - TC85)</p><p>There is user &nbsp;joanna_soares in MBP (TP1 - TS1 - TC1)</p><p>joanna_soares has no Activate Actuator created</p>
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| In the Main Navigation, select Rules &gt; Actions| Rules Action page is opened.| Pass |
| 2| Press Share Activate Actuator| Pop-up requests the username| Block |
| 3| Insert &nbsp;username: &nbsp;joanna_soares and click Share| The entity was sent successfully message is displayed| Block |
| 4| Logout, log in as &nbsp;joanna_soares and open&nbsp;Rules Action page (<a href="http://localhost:8080/MBP/view/rule-actions">http://localhost:8080/MBP/view/rule-actions</a>)&nbsp;| Activate Actuator is displayed in the list| Block |
#### Actual Results: 
- There is no Button to share the Action

**Comment by katja-seb** [comment]
https://mbp.testquality.com defect [D6](https://mbp.testquality.com/project/11022/result/2249320/defect/7508). Do not remove or edit.

**Comment by schneijan** [comment]
The "share" feature for entities does no longer exist; instead, sharing of entities can be done using the policies by @JakobBenz

**Comment by tatianegava** [comment]
I thought these Policies were only for Devices/Sensors/Actuators. I will exclude the test.
