### ISSUE TITLE
[Test-Tool] Reinstall Default Test Components - Existing Tests

### ISSUE THREAD

**Issue by katja-seb** [IPVS-AS/MBP#567]
If default sensors are reinstalled even though they are included in tests, an error is thrown. The sensor is created with a new ID when it is reintegrated into the MBP, but the test still contains the sensor with its old ID. 

There are 2 possibilities here: 

- The user is informed that one of the default components is used in a test and must first delete this test. 

- The contained components are also automatically exchanged in the test in the background.

**Comment by hirmerpl** [comment]
Option 2 is better, since like this, the users do not need to re-create all their tests, we should go for this one.
