### ISSUE TITLE
Deployment IP should be dynamic

### ISSUE THREAD

**Issue by hirmerpl** [IPVS-AS/MBP#6]

**Comment by hirmerpl** [comment]
What about running scripts?

**Comment by schneijan** [comment]
> What about running scripts?

Suggestion: After a change of the IP address was detected by the MBP, all currently deployed sensors are automatically redeployed. This should be possible, even with a different IP address of the MBP.

**Comment by hirmerpl** [comment]
Let's deal with this ticket later after another thorough discussion.
