### ISSUE TITLE
Javarize valuelogger

### ISSUE THREAD

**Issue by hirmerpl** [IPVS-AS/MBP#7]
When starting the tomcat server, the valuelogger functionality should be invoked in Java.
=> use ServletContextListener

**Comment by hirmerpl** [comment]
Analyze whether Mosquitto and MongoDB can be started in the ContextListener as well

**Comment by schneijan** [comment]
Finished the javarization. I'm not sure whether it would make sense to start mosquitto and the mongodb daemon automatically on startup though; both are supposed to be background processes and might be used by other applications/services as well.

**Comment by hirmerpl** [comment]
Mosquitto and MongoDB are operated as services, no manual start necessary.

**Comment by ana-silva** [comment]
remove invocation of valuelogger in install.sh:

https://github.com/IPVS-AS/MBP/blob/9c4ff617faa8fc0becabf358e869637e515cabd5/install.sh#L64
https://github.com/IPVS-AS/MBP/blob/9c4ff617faa8fc0becabf358e869637e515cabd5/install.sh#L65
https://github.com/IPVS-AS/MBP/blob/9c4ff617faa8fc0becabf358e869637e515cabd5/install.sh#L66
