### ISSUE TITLE
Wrong item gets deleted

### ISSUE THREAD

**Issue by hirmerpl** [IPVS-AS/MBP#82]
On deletion, the wrong device disappears in the model

How to reconstruate:
1) Load Model "New Model" (containing 2 devices) on http://192.168.209.194:8888/deploy/modeling_environment/view/model 
2) Delete the device on the right hand side

**Comment by amil-i** [comment]
Both devices got somehow the same canvas ID. I made the action independent of the ID. A new issue needs to be opened with the behavior that causes this problem (two components with same ID).
