### ISSUE TITLE
Remove blinking cursors

### ISSUE THREAD

**Issue by ana-silva** [IPVS-AS/MBP#93]
If the cursor is clicked somewhere in the MBP, a blinking cursor appears as if writing would be possible. This should not be the case.

**Comment by schneijan** [comment]
I am unable to reproduce this. Which browser are you using and on which page does the issue occur?

**Comment by schneijan** [comment]
Did the issue occur again? Otherwise I would suggest to close this one and reopen it on demand.

**Comment by hirmerpl** [comment]
not reproducable
